In [1]:
import pandas as pd

In [9]:
season_records = pd.DataFrame()

url = 'https://www.pro-football-reference.com/teams/cle/index.htm'
data = pd.read_html(url)

df = data[0]
df

   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                 Year                 Lg                 Tm
0                2022                NFL   Cleveland Browns
1                2021                NFL   Cleveland Browns
2                2020                NFL  Cleveland Browns*
3                2019                NFL   Cleveland Browns
4                2018                NFL   Cleveland Browns
..                ...                ...                ...
73               1950                NFL  Cleveland Browns*
74               1949               AAFC  Cleveland Browns*
75               1948               AAFC  Cleveland Browns*
76               1947               AAFC  Cleveland Browns*
77               1946               AAFC  Cleveland Browns*

   Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0  \
                    W                  L                  T
0                   7                 10                  0
1                   8                  9                  0
2                  11                  5                  0
3                   6                 10                  0
4                   7                  8                  1
..                ...                ...                ...
73                 10                  2                  0
74                  9                  1                  2
75                 14                  0                  0
76                 12                  1                  1
77                 12                  2                  0

   Unnamed: 6_level_0 Unnamed: 7_level_0 Points       ... Def Rank  \
          Div. Finish           Playoffs     PF   PA  ...      Yds
0            4th of 4                NaN    361  381  ...       14
1            3rd of 4                NaN    349  371  ...        5
2            3rd of 4           Lost Div    408  419  ...       17
3            3rd of 4                NaN    335  393  ...       22
4            3rd of 4                NaN    359  392  ...       30
..                ...                ...    ...  ...  ...      ...
73           1st of 6          Won Champ    310  144  ...        1
74           1st of 7          Won Champ    339  171  ...        3
75           1st of 4          Won Champ    389  190  ...        1
76           1st of 4          Won Champ    410  185  ...        2
77           1st of 4          Won Champ    423  137  ...        2

   Overall Rank                  Simple Rating System
            T/G Pts± Yds± out of                  MoV   SoS   SRS  OSRS  DSRS
0            16   18   11     32                 -1.2   1.1  -0.1   0.7  -0.9
1            20   20   10     32                 -1.3   0.0  -1.3  -2.7   1.3
2             9   16   14     32                 -0.7  -1.9  -2.6   0.3  -2.8
3            26   22   19     32                 -3.6   1.7  -1.9  -0.4  -1.5
4             8   20   26     32                 -2.1   1.7  -0.3  -1.0   0.6
..          ...  ...  ...    ...                  ...   ...   ...   ...   ...
73            2    1    3     13                 13.8   1.7  15.6   5.8   9.7
74            1    2    2      7                 14.0  -2.2  11.8   5.8   6.0
75            2    2    1      8                 14.2  -1.8  12.4   3.7   8.7
76            1    1    1      8                 16.1  -2.0  14.1   7.1   7.0
77            1    1    1      8                 20.4  -2.6  17.9   9.3   8.6

[78 rows x 29 columns]

In [13]:
df.MultiIndex.droplevel()

AttributeError: 'DataFrame' object has no attribute 'MultiIndex'